export const SET_LOGIN = 'SET_LOGIN';
export const SET_LOGOUT = 'SET_LOGOUT';
export const SET_USER = 'SET_USER';
export const REG_SUCCESS = 'REG_SUCCESS';
export const REG_FAILED = 'REG_FAILED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const RESET_MSG = 'RESET_MSG';

export const REQ_GANTI_PASSWORD = 'REQ_GANTI_PASSWORD';
export const REQ_GANTI_PASSWORD_SUCCESS = 'REQ_GANTI_PASSWORD_SUCCESS'; 
export const REQ_GANTI_PASSWORD_FAILED = 'REQ_GANTI_PASSWORD_FAILED';

